-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 23:33:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema iformal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iformal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iformal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `iformal` ;

-- -----------------------------------------------------
-- Table `iformal`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iformal`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(20) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `contato` VARCHAR(20) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `iformal`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iformal`.`servicos` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(20) NULL DEFAULT NULL,
  `data_servico` DATE NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  `preco` FLOAT NOT NULL,
  `servico_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `iformal`.`agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iformal`.`agendamentos` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_servico` INT NULL DEFAULT NULL,
  `data_servico` DATE NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_servico` (`id_servico` ASC) VISIBLE,
  CONSTRAINT `agendamentos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `iformal`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL,
  CONSTRAINT `agendamentos_ibfk_2`
    FOREIGN KEY (`id_servico`)
    REFERENCES `iformal`.`servicos` (`id_servico`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
